module.exports = {
    deposit: 'deposit',
    withdraw: 'withdraw',
    exchange: 'exchange',
    redeem: 'redeem',
    build: 'build',
    send_buildings: 'send_buildings',
    buy_fruit: 'buy_fruit',
    send_fruit: 'send_fruit',
    buy_vegetables: 'buy_vegetables',
    send_vegetables: 'send_vegetables',
    sell_plants: 'sell_plants',
    sell_products: 'sell_products',
    det_fruit: 'det_fruit',
    det_vegetables: 'det_vegetables',
    det_products: 'det_products',
    next_step: 'next_step',
    skip: 'skip',
    step2: 'step2',
    step3: 'step3',
    step4: 'step4',
    step5: 'step5',
    step6: 'step6',
    finish: 'finish',
    buildChicken: 'buildChicken',
    buildPig: 'buildPig',
    buildSheepdog: 'buildSheepdog',
    buildCowshed: 'buildCowshed',
    buildHive: 'buildHive',
    buildTurkey: 'buildTurkey',
    // ======== FRUIT =========
    buyApple: 'buyApple',
    buyPear: 'buyPear',
    buyGrapes: 'buyGrapes',
    buyStrawberries: 'buyStrawberries',
    buyCherries: 'buyCherries',
    buyPeach: 'buyPeach',
    // ======== VEGETABLES =========
    buyTomato: 'buyTomato',
    buyEggplant: 'buyEggplant',
    buyCarrots: 'buyCarrots',
    buyCorn: 'buyCorn',
    buyPepper: 'buyPepper',
    buyPotatoes: 'buyPotatoes',
    
    feedback: 'feedback',
    training: 'training',
    faq: 'faq',
    idea: 'idea',
    
    changeName: 'changeName',
    
    check1: 'check1',
    check2: 'check2',
    check3: 'check3',
    check4: 'check4',
    check5: 'check5',
    check6: 'check6',
    check7: 'check7',
    check8: 'check8'
}